# Generated by Django 4.1.7 on 2023-04-26 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mng", "0005_customers_village_alter_mainamount_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaser",
            name="w_amount",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mainamount",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 15, 9, 43, 956795)
            ),
        ),
        migrations.AlterField(
            model_name="purchaser",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 26, 15, 9, 43, 956795)
            ),
        ),
    ]
