# Generated by Django 4.2 on 2023-05-25 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0008_customers_status_mainamount_status_product_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exdate', models.DateTimeField(default=datetime.datetime(2023, 5, 25, 13, 20, 8, 639415))),
                ('exname', models.CharField(max_length=100)),
                ('examount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='mainamount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 13, 20, 8, 637415)),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 13, 20, 8, 638415)),
        ),
    ]
