# Generated by Django 4.2 on 2023-05-25 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0009_expenses_alter_mainamount_date_alter_purchaser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='exdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 13, 21, 35, 609890)),
        ),
        migrations.AlterField(
            model_name='mainamount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 13, 21, 35, 607891)),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 13, 21, 35, 608890)),
        ),
    ]
