# Generated by Django 4.2 on 2023-05-29 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0011_expenses_expstatus_alter_expenses_exdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='stt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaser',
            name='stt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 13, 27, 31, 442902)),
        ),
        migrations.AlterField(
            model_name='mainamount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 13, 27, 31, 440902)),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 13, 27, 31, 441902)),
        ),
    ]
