# Generated by Django 4.2 on 2023-05-29 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0012_expenses_stt_purchaser_stt_alter_expenses_exdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailystatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 5, 29, 13, 38, 31, 139155))),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('bkamount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='stt',
        ),
        migrations.RemoveField(
            model_name='purchaser',
            name='bkamount',
        ),
        migrations.RemoveField(
            model_name='purchaser',
            name='stt',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 13, 38, 31, 138155)),
        ),
        migrations.AlterField(
            model_name='mainamount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 13, 38, 31, 135155)),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 13, 38, 31, 136155)),
        ),
    ]
