# Generated by Django 4.2 on 2023-05-30 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0013_dailystatus_remove_expenses_stt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 5, 30, 11, 33, 14, 698965))),
                ('purchaser_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('rate', models.IntegerField(default=0)),
                ('weight', models.CharField(max_length=100)),
                ('w_amount', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='dailystatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 11, 33, 14, 701967)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 11, 33, 14, 700965)),
        ),
        migrations.AlterField(
            model_name='mainamount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 11, 33, 14, 696966)),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 11, 33, 14, 697965)),
        ),
    ]
