# Generated by Django 4.2 on 2023-05-30 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0014_sales_alter_dailystatus_date_alter_expenses_exdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('w_amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='dailystatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 13, 53, 32, 814962)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 13, 53, 32, 813962)),
        ),
        migrations.AlterField(
            model_name='mainamount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 13, 53, 32, 810962)),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 13, 53, 32, 811961)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 13, 53, 32, 812961)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
