# Generated by Django 4.2 on 2023-05-31 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0015_stock_alter_dailystatus_date_alter_expenses_exdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailystatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 12, 17, 51, 803200)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 12, 17, 51, 801321)),
        ),
        migrations.AlterField(
            model_name='mainamount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 12, 17, 51, 798338)),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 12, 17, 51, 799322)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 12, 17, 51, 800337)),
        ),
    ]
