# Generated by Django 4.2 on 2023-06-01 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0017_stock_rate_alter_dailystatus_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesdt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 6, 1, 19, 49, 4, 717218))),
                ('purchaser_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('old_rate', models.IntegerField(default=0)),
                ('old_amount', models.IntegerField()),
                ('new_rate', models.IntegerField(default=0)),
                ('new_amount', models.IntegerField()),
                ('profit', models.IntegerField(default=0)),
                ('weight', models.CharField(max_length=100)),
                ('w_amount', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='dailystatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 19, 49, 4, 715222)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 19, 49, 4, 714218)),
        ),
        migrations.AlterField(
            model_name='mainamount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 19, 49, 4, 710219)),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 19, 49, 4, 711219)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 19, 49, 4, 712219)),
        ),
    ]
