# Generated by Django 4.2 on 2023-06-18 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0024_alter_dailystatus_date_alter_expenses_exdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='dailystatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 27, 54, 306585)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 27, 54, 305585)),
        ),
        migrations.AlterField(
            model_name='mainamount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 27, 54, 302586)),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 27, 54, 303585)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 27, 54, 304585)),
        ),
        migrations.AlterField(
            model_name='salesdt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 27, 54, 308585)),
        ),
    ]
