# Generated by Django 4.2 on 2023-06-18 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0025_product_image_alter_dailystatus_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 43, 57, 105934)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 43, 57, 104931)),
        ),
        migrations.AlterField(
            model_name='mainamount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 43, 57, 100932)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 43, 57, 101931)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 43, 57, 103931)),
        ),
        migrations.AlterField(
            model_name='salesdt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 19, 43, 57, 107933)),
        ),
    ]
