# Generated by Django 4.2 on 2023-06-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dglog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuser',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
