# Generated by Django 4.2 on 2023-06-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dglog', '0002_nuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuser',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
