# Generated by Django 4.2 on 2023-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dglog', '0003_alter_nuser_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuser',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
